### ISSUE TITLE
installing takari team on top of STS 3.9.1

### ISSUE THREAD

**Issue by dantran** [takari/io.takari.m2e.team#4]
Hi I have a command line automation to swap out STS m2e and m2e logback, in order to install takari team

starting with STS 3.9.1 and latest takari team, I run into this issue

Installing io.takari.m2e.team.feature.feature.group 0.1.0.201710190128.
Installation failed.
Cannot complete the install because one or more required items could not be found.
 Software being installed: Takari TEAM for Eclipse 0.1.0.201710190128 (io.takari.m2e.team.feature.feature.group 0.1.0.201710190128)
 Missing requirement: m2e logback configuration 1.9.0.20171019-0117 (org.eclipse.m2e.logback.configuration 1.9.0.20171019-0117) requires 'bundle ch.qos.logback.slf4j 0.9.24' but it could not be found

is there any way the Takari team can help fixing this?  ch.qos.logback.slf4j 0.9.24 is quite old and I can't find it

the workaround is having users to install Takari team manually using eclipse UI which prefer to avoid

**Comment by ifedorenko** [comment]
This feature is meant to simplify manual installation using eclipse ui. For automated installations use individual components you need. You can see component repositories in `pom.xml`.
